### ISSUE TITLE
Part 2 of the assignment

### ISSUE THREAD

**Issue by lsazama716** [unosec/project#31]
Using findings from the DFD-based threat analysis from part 1 of this assignment:

1. Review your OSS project for design-related issues.
2. Summarize your observations, in particular, highlight the gaps.

**Comment by DillonPetschke** [comment]
Added observations to our main document related to the security controls around file read\write access.

**Comment by lsazama716** [comment]
Edited the observations and added the "Investigating" list.

**Comment by lsazama716** [comment]
No more suggestions being made. Closing to submit the assignment.
