### ISSUE TITLE
Run SonarQube against Nextcloud:main

### ISSUE THREAD

**Issue by cosmicspork** [unosec/project#34]
Found: 
- 609 "Bugs"
- 1 "Vulnerability" 
- 734 Security Hotspots

Most of the issues labeled as bugs are PHP things like using 'require' instead of 'require_once' or 'include' => 'include_once'. There are also some HTML markup issues, unreachable code, output that is never returned, unused object instantiation, missing alt text and descriptions, and a couple variable reuse issues.

The vuln is that a key length of 512 bits found in tests/Core/Service/LoginFlowV2ServiceUnitTest.php:124 SonarQube says it should be 2048 bits.

The security hot spots are mostly centered around the use of HTTP in CalDAV and tests, the use of hard coded IP addresses in tests, and passwords in tests. There are some other things like the use of pseudorandom number generators, bidirectional characters, and cookies without the secure flag.

**Comment by cosmicspork** [comment]
The overall scored from SonarQube are:
- Maintainability [A]
- Reliability [D]
- Security [D]
- Security Review [D]

Please let me know if you want additional information as I have SonarQube running in a docker container on my local network and I don't want to go through the effort to expose it to the internet.

**Comment by lsazama716** [comment]
Added this issue to our "Code Analysis" project.

**Comment by cosmicspork** [comment]
Also included scans of plugins: calendar, talk, and mail. My SonarQube docker container has been shared with the group for analysis.
