### ISSUE TITLE
Run ZAP against Nextcloud

### ISSUE THREAD

**Issue by cosmicspork** [unosec/project#35]
Using linuxserver/docker-nextcloud container on my local network.

**Comment by cosmicspork** [comment]
Here is the generated report: [ZAP_report_Nextcloud.zip](https://github.com/unosec/project/files/10071814/ZAP_report_Nextcloud.zip)

Please let me know if you want additional scans.

**Comment by lsazama716** [comment]
Added this issue to our "Code Analysis" project.
