### ISSUE TITLE
Create a checklist-based approach

### ISSUE THREAD

**Issue by lsazama716** [unosec/project#38]

**Comment by lsazama716** [comment]
Identify a list of 5-10 CWEs (as specific as possible) that would be most important as findings from your manual or automated code review.

**Comment by DillonPetschke** [comment]
Adding CWE's related to our misuse cases and assurance claims

CWE-434: Unrestricted Upload of File with Dangerous Type
CWE-22: Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')
CWE-125: Out-of-bounds Read
CWE-287: Improper Authentication
CWE-862: Missing Authorization
CWE-798: Use of Hard-coded Credentials
CWE-276: Incorrect Default Permissions
CWE-94: Improper Control of Generation of Code ('Code Injection')
CWE-78: Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')

**Comment by lsazama716** [comment]
These have been added to the markdown file.
