### ISSUE TITLE
What challenges do you expect before starting code review?

### ISSUE THREAD

**Issue by lsazama716** [unosec/project#39]

**Comment by lsazama716** [comment]
My anticipated challenge is that it is a very large, mature program. What vulnerabilities will we actually find? And how much work will it be to find a vulnerability?

**Comment by DillonPetschke** [comment]
My expected challenges relate to my inexperience in PHP code review tooling and analysis of results. With 425 thousand lines of code, a manual code review will not be possible with our time constraints. Therefore, we will need to utilize automated tooling to improve our efficiency

**Comment by tltglitch** [comment]
My anticipated challenge is about the third party applications and what vulnerabilities they may add to the nextcloud platform itself when added or installed in the system and how these vulnerabilities can be remediated or isolated even when the developers are unwilling to fix them.

**Comment by lsazama716** [comment]
Added to the Reflections section.
